### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ludberg** [apockill/clai#3]
I followed you install instructions and tried 'clai Write an email..' and go
`
NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev
`

Any ideas?

**Comment by apockill** [comment]
Ah thank you for notifying me. I must have had those packages already installed. 

Can you test that command and running `clai` again? If it works, I'll add them to the README instructions.

**Comment by ludberg** [comment]
I got through it yesterday but also had to install tesseract and scrot

**Comment by apockill** [comment]
Ahh, my bad. I think I published to pypi the version from this branch: https://github.com/apockill/clai/tree/feature/tesseract

If you go there, you'll see some instructions to install `tesseract` and `scrot`. Thank you for your feedback, I'll add `python3-tk` and `python3-dev` to the dependencies.
