### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by ludberg** [apockill/clai#4]
Hi, 

When I'm using 'clai <swedish text>' in my console it works fine. 
But, when I'm using your fork of shin to enable clai in all inputs I get the following error after using 'clai <same swedish text>':

`I'm sorry, but the prompt is not in English, hence I cannot provide an answer as I have been programmed to only respond in English. Please provide a prompt in English.` 

How can I overcome this hurdle?

**Comment by apockill** [comment]
Hmm, it shouldn't make a difference whether you're running on a terminal or within `shin`. When running with `shin`, it passes the context directly to `clai`, without changing it.

This is probably a statistical anomaly- after all, GPT models can be flaky at times.
